# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
